# Compare allocation-rule outputs generated by Python.
root <- getwd()
file <- file.path(root, "outputs", "tables", "allocation_rule_comparison.csv")
if (file.exists(file)) {
  d <- read.csv(file)
  tab <- aggregate(resource_share ~ scenario + actor_group, data = d, FUN = mean)
  write.csv(tab, file.path(root, "outputs", "tables", "r_allocation_rule_summary.csv"), row.names = FALSE)
} else {
  message("Run python/resource_allocation_feedback.py first.")
}
