article_root <- if (basename(getwd()) == "r") normalizePath("..") else normalizePath(".")
out_dir <- file.path(article_root, "outputs", "figures")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
delay <- seq(1, 18, by = 0.5)
resilience <- pmax(0, pmin(1, 0.68 - 0.035 * delay + 1.2 * 0.08 - 1.4 * 0.05))
png(file.path(out_dir, "delay_threshold_visualization.png"), width = 900, height = 600)
plot(delay, resilience, type = "l", xlab = "Implementation delay", ylab = "Resilience", main = "Delay Sensitivity Threshold Example")
abline(h = 0.50, lty = 2)
dev.off()
