source(file.path(dirname(sys.frame(1)$ofile), "_workflow_utils.R"))
root <- article_root(); ensure_dirs(root)
capacity_path <- file.path(root, "outputs", "tables", "implementation_capacity_summary.csv")
if (!file.exists(capacity_path)) stop("Run python/run_all_public_policy_workflows.py before this R script.")
capacity <- read.csv(capacity_path)
write.csv(capacity, file.path(root, "outputs", "tables", "r_implementation_capacity_summary.csv"), row.names = FALSE)
print(capacity)
