root <- normalizePath(file.path(dirname(sys.frame(1)$ofile), ".."), mustWork = FALSE)
capacity <- read.csv(file.path(root, "data", "synthetic_implementation_capacity.csv"))
outputs <- file.path(root, "outputs", "tables")
dir.create(outputs, recursive = TRUE, showWarnings = FALSE)
metric_cols <- c("staffing", "knowledge", "data_systems", "institutional_memory", "authority")
capacity$implementation_capacity_score <- rowMeans(capacity[, metric_cols])
capacity$capacity_class <- ifelse(capacity$implementation_capacity_score >= 60, "stronger", ifelse(capacity$implementation_capacity_score >= 50, "moderate", "fragile"))
write.csv(capacity, file.path(outputs, "implementation_capacity_r_summary.csv"), row.names = FALSE)
print(capacity)
