script_dir <- dirname(normalizePath(sub("--file=", "", grep("--file=", commandArgs(FALSE), value = TRUE)[1]), mustWork = FALSE))
if (is.na(script_dir) || length(script_dir) == 0) script_dir <- getwd()
source(file.path(script_dir, "public_policy_indicator_visualization.R"))
source(file.path(script_dir, "policy_outcome_trajectory_plots.R"))
source(file.path(script_dir, "public_trust_trajectory_plots.R"))
source(file.path(script_dir, "administrative_burden_plots.R"))
source(file.path(script_dir, "distributional_policy_tables.R"))
source(file.path(script_dir, "implementation_capacity_summary.R"))
cat("R public policy workflow complete.\n")
