source(file.path(dirname(sys.frame(1)$ofile), "_workflow_utils.R"))
root <- article_root(); ensure_dirs(root)
impact_path <- file.path(root, "outputs", "tables", "distributional_policy_impact.csv")
if (!file.exists(impact_path)) stop("Run python/run_all_public_policy_workflows.py before this R script.")
impacts <- read.csv(impact_path)
impacts <- impacts[order(impacts$net_policy_impact), ]
write.csv(impacts, file.path(root, "outputs", "tables", "r_distributional_policy_diagnostics.csv"), row.names = FALSE)
fig <- file.path(root, "outputs", "figures", "net_policy_impact_by_group.png")
png(fig, width = 1000, height = 650)
barplot(impacts$net_policy_impact, names.arg = impacts$group, las = 2, main = "Net Policy Impact by Group", ylab = "Benefits - burdens - risks")
abline(h = 0, lty = 2)
dev.off()
print(impacts)
cat("Wrote", fig, "\n")
