# Base R placeholder for organizational learning summaries.
root <- normalizePath(file.path(dirname(sys.frame(1)$ofile %||% "r/organizational_learning_plots.R"), ".."), mustWork = FALSE)
message("Organizational learning plots placeholder. Use outputs/tables generated by Python scripts.")
